/**
 * Reads convex/seed-skills/*.md, validates size (<= 512 KB per file),
 * and writes convex/seed_skills_content.generated.ts with contentBySlug. For local use only.
 */

import * as fs from "fs";
import * as path from "path";
import {
  CONTENT_MARKDOWN_MAX_BYTES,
  buildContentBySlugFromEntries,
} from "../convex/lib/seed_skills_build";
import { getBackendRoot } from "./local-paths";

/** Escapes content for use inside a template literal in generated TS. */
function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

/**
 * Entry point: reads all .md in convex/seed-skills/, validates size, writes seed_skills_content.generated.ts.
 * If no .md files exist, writes an empty contentBySlug so Convex import still works.
 */
function main(): void {
  const root = getBackendRoot("seed-skills");
  const skillsDir = path.join(root, "convex", "seed-skills");
  const outPath = path.join(root, "convex", "seed_skills_content.generated.ts");

  const fileEntries = fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith(".md"))
    .map((d) => d.name);

  const entries: Array<{ slug: string; content: string }> = fileEntries.map(
    (file) => {
      const slug = file.replace(/\.md$/, "");
      const content = fs.readFileSync(
        path.join(skillsDir, file),
        "utf-8",
      );
      return { slug, content };
    },
  );

  let contentBySlug: Record<string, string>;
  try {
    contentBySlug = buildContentBySlugFromEntries(
      entries,
      CONTENT_MARKDOWN_MAX_BYTES,
    );
  } catch (err) {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  }

  const lines: string[] = [
    "// Generated by scripts/seed-skills-generate.ts. Do not edit by hand.",
    "",
    "export const contentBySlug: Record<string, string> = {",
  ];

  for (const [slug, content] of Object.entries(contentBySlug)) {
    const escaped = escapeForTemplateLiteral(content);
    lines.push(`  ${JSON.stringify(slug)}: \`${escaped}\`,`);
  }

  lines.push("};");
  lines.push("");

  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");
  console.log(`Wrote ${Object.keys(contentBySlug).length} skills to convex/seed_skills_content.generated.ts`);
}

main();
